# NumPy Basics

In this notebook, we will learn the most important NumPy ideas step by step.

You will practice:
- creating arrays
- checking shape and dtype
- indexing and slicing
- working with 2D arrays
- thinking of images as arrays
- doing arithmetic and matrix operations

Please read each cell carefully and run it in order.

*Disclaimer*: This notebook takes inspiration from this kaggle tutorial [link](https://www.kaggle.com/code/legendadnan/numpy-tutorial-for-beginners-data-science#NumPy-Operations)

## NumPy Hello World

Let us start with simple NumPy examples.

NumPy is a library for working with arrays.  

An array is like a list, but it is more powerful for numerical computing.

In [ ]:
# This is the standard import for NumPy.
# We will use the alias "np" throughout the notebook.

import numpy as np

In [2]:
# Create a simple NumPy array from characters.
# This is just a fun "hello world" example to show that arrays can hold strings too.

hello_world = np.array(["h", "e", "l", "l", "o", "w", "o", "r", "l", "d"])
print(hello_world)

['h' 'e' 'l' 'l' 'o' 'w' 'o' 'r' 'l' 'd']


In [3]:
# Create an array of numbers from 0 to 24.
# np.arange(25) gives us 25 values: 0, 1, 2, ..., 24.

arr = np.arange(25)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [4]:
# Every NumPy array has a data type.
# The dtype tells us what kind of values are stored in the array.

print("dtype:", arr.dtype)

dtype: int64


## Shape

The shape of an array tells us how many dimensions it has and how many items are in each dimension.

For example:
- a vector has shape like `(25,)`
- a matrix has shape like `(5, 5)`

In [5]:
# Reshape the 1D array into a 5x5 matrix.
# This does not change the values, only the layout.

arr_2d = arr.reshape(5, 5)
print(arr_2d)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [6]:
# Check the shape of the original 1D array.

print("Original shape:", arr.shape)

Original shape: (25,)


In [7]:
# Check the shape of the reshaped 2D array.

print("Reshaped array shape:", arr_2d.shape)

Reshaped array shape: (5, 5)


## Indexing

Indexing means selecting one item from an array.

Remember:
- NumPy uses zero-based indexing
- the first item is at index 0
- the second item is at index 1

In [8]:
# Access a single value from the 1D array.
# This gets the value at index 8.

arr[8]

np.int64(8)

In [9]:
# Get a slice of values from index 1 up to, but not including, index 5.
# This is a very common NumPy operation.

arr[1:5]

array([1, 2, 3, 4])

## Arrays in Two Dimensions

2D arrays are very important because they behave like tables or matrices.

You can think of them as:
- rows
- columns

In [10]:
# Create a small 2D array manually.

arr_2d = np.array([
    [5, 10, 15],
    [20, 25, 30],
    [35, 40, 45]
])

print(arr_2d)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [11]:
# Select the second row.
# In NumPy, row indexing starts from 0.

arr_2d[1]

array([20, 25, 30])

In [12]:
# Get one individual element.
# Both forms below do the same thing.

print(arr_2d[1][0])
print(arr_2d[1, 0])

20
20


In [13]:
# Slice a 2D array.
# This selects the top-right 2x2 block.

arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

## Image-like Arrays

Images can also be stored as NumPy arrays.

A color image usually has shape:
- `(height, width, channels)`

For RGB images, the number of channels is usually 3:
- red
- green
- blue

In [14]:
# Create a blank image-like array.
# This is a 64x64 image with 3 color channels.
# dtype=np.uint8 means pixel values are integers from 0 to 255.

img = np.zeros((64, 64, 3), dtype=np.uint8)

print("shape:", img.shape)
print("dtype:", img.dtype)

shape: (64, 64, 3)
dtype: uint8


In [15]:
# Extract the red channel.
# The result is a 2D array with shape (64, 64).

red = img[:, :, 0]
print(red.shape)

(64, 64)


In [16]:
# Crop the top-left 32x32 region.
# Slicing is a powerful way to extract part of an image.

crop = img[:32, :32]
print(crop.shape)

(32, 32, 3)


In [17]:
# Flip the image horizontally.
# The ::-1 slice reverses the order along the width dimension.

flipped = img[:, ::-1]
print(flipped.shape)

(64, 64, 3)


## Arithmetic Operations

NumPy lets you do math directly on arrays.

This is one of the main reasons NumPy is so useful.

In [18]:
# Create a small numeric array for arithmetic examples.

arr = np.arange(0, 10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [19]:
# Element-wise addition.
# Each value is added to the matching value in the other array.

print(arr + arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [20]:
# Element-wise multiplication.

print(arr * arr)

[ 0  1  4  9 16 25 36 49 64 81]


In [21]:
# Element-wise subtraction.

print(arr - arr)

[0 0 0 0 0 0 0 0 0 0]


In [22]:
# Division by the array itself.
# The first value is 0 / 0, which becomes NaN.
# NumPy will usually show a warning, but it will still continue.

print(arr / arr)

[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.]


/tmp/ipykernel_26255/4136592861.py:5: RuntimeWarning: invalid value encountered in divide
  print(arr / arr)


In [23]:
# Division by zero from the other direction.
# 1 / 0 becomes infinity.

print(1 / arr)

[       inf 1.         0.5        0.33333333 0.25       0.2
 0.16666667 0.14285714 0.125      0.11111111]


/tmp/ipykernel_26255/3596056618.py:4: RuntimeWarning: divide by zero encountered in divide
  print(1 / arr)


In [24]:
# Power operation.
# This raises each element to the third power.

print(arr ** 3)

[  0   1   8  27  64 125 216 343 512 729]


## Matrix Operations

Matrices are 2D arrays, and they are very common in machine learning.

In this section, we will practice:
- addition
- multiplication
- matrix multiplication
- transpose
- averages
- broadcasting
- distance calculations

In [25]:
# Create two matrices.

A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([
    [7, 8, 9],
    [10, 11, 12]
])

print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Shape of A:", A.shape)

Matrix A:
 [[1 2 3]
 [4 5 6]]
Matrix B:
 [[ 7  8  9]
 [10 11 12]]
Shape of A: (2, 3)


In [26]:
# Element-wise addition.
# This works because A and B have the same shape.

print("A + B:\n", A + B)

A + B:
 [[ 8 10 12]
 [14 16 18]]


In [27]:
# Element-wise multiplication.
# This is NOT matrix multiplication.
# It multiplies matching entries.

print("A * B:\n", A * B)

A * B:
 [[ 7 16 27]
 [40 55 72]]


In [28]:
# Scalar multiplication.
# Every element in A is multiplied by 2.

print("A * 2:\n", A * 2)

A * 2:
 [[ 2  4  6]
 [ 8 10 12]]


In [29]:
# Matrix multiplication.
# The number of columns in A must match the number of rows in C.

C = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

result = A @ C

print("A shape:", A.shape)
print("C shape:", C.shape)
print("A @ C:\n", result)

A shape: (2, 3)
C shape: (3, 2)
A @ C:
 [[22 28]
 [49 64]]


In [30]:
# Transpose swaps rows and columns.

A_T = A.T

print("A:\n", A)
print("A transpose:\n", A_T)

A:
 [[1 2 3]
 [4 5 6]]
A transpose:
 [[1 4]
 [2 5]
 [3 6]]


In [31]:
# Mean of all elements in the matrix.

print("Mean of all elements:", A.mean())

Mean of all elements: 3.5


In [32]:
# Mean across rows.
# axis=1 means "go across columns for each row".

print("Mean across rows:", A.mean(axis=1))

Mean across rows: [2. 5.]


In [33]:
# Mean across columns.
# axis=0 means "go down rows for each column".

print("Mean across columns:", A.mean(axis=0))

Mean across columns: [2.5 3.5 4.5]


In [34]:
# Sum across columns.

print("Sum across columns:", A.sum(axis=0))

Sum across columns: [5 7 9]


In [35]:
# Broadcasting example.
# A 1D vector can be added to each row of A automatically.

v = np.array([1, 1, 1])

result = A + v

print("Vector v:", v)
print("A + v:\n", result)

Vector v: [1 1 1]
A + v:
 [[2 3 4]
 [5 6 7]]


In [ ]:
# Euclidean distance between two vectors.

x = np.array([1.0, 2.0, 3.0])
y = np.array([4.0, 5.0, 6.0])

distance = np.linalg.norm(x - y)

print("Distance between x and y:", distance)

Distance between x and y: 5.196152422706632
